name: test

on: 
  workflow_dispatch:

jobs:
  use:
    environment: test
    name: use
    runs-on: ["${{ join(fromJson(vars.TAGS), ', ') }}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo ${{ fromJson(vars.TAGS)[0] }}
#  create:
#    environment: test
#    name: create
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Test
#        id: Test
#        run: |
#          echo "TAG=${{ join(fromJson(vars.TAGS), ', ') }}" >> $GITHUB_OUTPUT
#    outputs:
#      TAG: ${{ steps.Test.outputs.TAG }}
#  test:
#    needs: create
#    environment: test
#    name: test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Test
#        run: |
#          echo ${{needs.create.outputs.TAG}}