name: test

on: 
  workflow_dispatch:

jobs:
  create:
    environment: test
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        id: Test
        run: |
          echo "TAG=${{ join(fromJson(vars.TAGS), ', ') }}" >> $GITHUB_OUTPUT
    outputs:
      TAG: ${{ steps.Test.outputs.TAG }}
  test:
    needs: create
    environment: test
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo ${{needs.prep.outputs.TAG }}
  use:
    needs: create
    environment: test
    name: test
    runs-on: ['${{needs.prep.outputs.TAG }}']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo ${{ fromJson(vars.TAGS)[0] }}