name: test

on: 
  workflow_dispatch:
# Environment VARS = ["ubuntu", "self-hosted"]
jobs:
  create:
    environment: test
    name: create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Tag
        id: Create
        run: |
          echo "TAG=${{ vars.TAGS }}" >> $GITHUB_OUTPUT
      - name: Set outputs
        run: |
          echo ${{ steps.Create.outputs.TAG }}
    outputs:
      TAG: ${{ steps.Create.outputs.TAG }}

  use:
    needs: create
    environment: test
    name: Use Var
    runs-on: ${{needs.create.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo ${{ fromJson(vars.TAGS)[0] }}