name: test

on: 
  workflow_dispatch:
# Environment VARS = ["ubuntu", "self-hosted"]
jobs:
  create:
    environment: test
    name: create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        id: Test
        run: |
          echo "TAG=${{ join(fromJson(vars.TAGS), '","') }}" >> $GITHUB_OUTPUT
    outputs:
      TAG: ${{ steps.Test.outputs.TAG }}

  use:
    needs: create
    environment: test
    name: use
    runs-on: ['${{needs.create.outputs.TAG }}']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo ${{ fromJson(vars.TAGS)[0] }}