name: test

on: 
  workflow_dispatch:

jobs:
  test:
    environment: test
    name: test
    runs-on: ${{ fromJson(vars.TAGS) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo ${{ fromJson(vars.TAGS) }}